import {
  AdminUser,
  MedicineItem,
  RetailProductItem,
  InventoryMovement,
  AdminOrder,
  CustomerCRM,
  PromotionRule,
  BannerItem,
  SiteDesignConfig,
  SeoConfig,
  BlogPost,
  CommercialStoreSettings,
  IntegrationsConfig,
  ActivityLog,
  TrashItem,
  DeliveryRate,
  PickupPoint,
} from "@/types/admin";
import { farmaboyConfig } from "./farmaboy";

export const initialAdminUsers: AdminUser[] = [
  {
    id: "adm-01",
    name: "Dr. Roberto Salamanca",
    email: "admin@farmaboy.com.co",
    role: "SUPER_ADMIN",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
    lastLogin: "Hoy 14:10",
    ipAddress: "190.158.204.14",
    isActive: true,
  },
  {
    id: "adm-02",
    name: "Dra. Carolina Vargas (Q.F.)",
    email: "farmacia@farmaboy.com.co",
    role: "FARMACEUTICO",
    lastLogin: "Ayer 18:30",
    ipAddress: "186.84.92.10",
    isActive: true,
  },
  {
    id: "adm-03",
    name: "Santiago Gómez (Comercial)",
    email: "ventas@farmaboy.com.co",
    role: "VENTAS",
    lastLogin: "Hoy 09:20",
    ipAddress: "190.158.204.88",
    isActive: true,
  },
  {
    id: "adm-04",
    name: "Valentina Morales",
    email: "editor@farmaboy.com.co",
    role: "EDITOR",
    lastLogin: "03 Sep 16:45",
    isActive: true,
  },
  {
    id: "adm-05",
    name: "Andrés Pinzón",
    email: "soporte@farmaboy.com.co",
    role: "SOPORTE",
    lastLogin: "Hoy 11:05",
    isActive: true,
  },
];

export const initialMedicines: MedicineItem[] = [
  {
    id: "med-01",
    name: "Acetaminofén 500 mg (Caja x 100 Tab)",
    genericName: "Paracetamol",
    barcode: "7702132001145",
    sku: "MED-ACT-500-100",
    category: "Medicamentos",
    subCategory: "Analgésicos y Antipiréticos",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    description: "Analgésico y antipirético de primera línea para el alivio del dolor de cabeza, malestar general y control de la fiebre en adultos y niños mayores de 12 años.",
    shortDescription: "Caja x 100 Tabletas. Alivio eficaz de fiebre y dolor.",
    costPriceCOP: 8200,
    salePriceCOP: 12500,
    previousPriceCOP: 14000,
    marginPercent: 34.4,
    currentStock: 48,
    minStock: 20,
    maxStock: 200,
    lotNumber: "LOT-2026-A88",
    expiryDate: "2027-08-30",
    physicalLocation: "Estante 2 - Pasillo A (Medicamentos)",
    requiresPrescription: false,
    status: "ACTIVO",
    supplier: "Laboratorios Lafrancol / Genfar",
    pharmaInfo: {
      principioActivo: "Acetaminofén (Paracetamol)",
      concentracion: "500 mg por tableta",
      formaFarmaceutica: "Tabletas recubiertas",
      laboratorio: "Genfar S.A.",
      registroSanitarioINVIMA: "INVIMA 2021M-001248-R3",
      indicaciones: "Tratamiento sintomático del dolor leve a moderado y estados febriles.",
      contraindicaciones: "Hipersensibilidad al principio activo. Insuficiencia hepática o renal severa.",
      precauciones: "No exceder la dosis máxima diaria de 4 gramos para evitar daño hepático.",
      formaDeUso: "Vía oral con abundante agua. 1 tableta cada 6 a 8 horas según criterio.",
      almacenamiento: "Conservar a temperatura no mayor a 30°C en lugar seco y protegido de la luz.",
    },
  },
  {
    id: "med-02",
    name: "Ibuprofeno 800 mg (Caja x 30 Tab)",
    genericName: "Ibuprofeno",
    barcode: "7702132002237",
    sku: "MED-IBU-800-30",
    category: "Medicamentos",
    subCategory: "Antiinflamatorios no esteroideos (AINEs)",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    description: "Antiinflamatorio no esteroideo indicado para dolores osteomusculares, inflamación articular y molestias postraumáticas.",
    shortDescription: "Caja x 30 Tabletas. Antiinflamatorio y analgésico potente.",
    costPriceCOP: 11000,
    salePriceCOP: 16800,
    marginPercent: 34.5,
    currentStock: 24,
    minStock: 15,
    maxStock: 100,
    lotNumber: "LOT-2026-B12",
    expiryDate: "2027-04-15",
    physicalLocation: "Estante 2 - Pasillo B",
    requiresPrescription: true,
    status: "ACTIVO",
    supplier: "Laboratorios MK / Tecnoquímicas",
    pharmaInfo: {
      principioActivo: "Ibuprofeno",
      concentracion: "800 mg",
      formaFarmaceutica: "Tabletas recubiertas",
      laboratorio: "Tecnoquímicas S.A.",
      registroSanitarioINVIMA: "INVIMA 2020M-008922-R2",
      indicaciones: "Procesos inflamatorios dolorosos agudos y crónicos, artritis, lumbalgia.",
      contraindicaciones: "Úlcera péptica activa, hemorragia gastrointestinal, embarazo en tercer trimestre.",
      precauciones: "Administrar preferiblemente con las comidas.",
      formaDeUso: "Vía oral 1 tableta cada 8 a 12 horas.",
      almacenamiento: "Almacenar a menos de 30°C.",
    },
  },
  {
    id: "med-03",
    name: "Amoxicilina 500 mg (Caja x 50 Cápsulas)",
    genericName: "Amoxicilina Trihidrato",
    barcode: "7703345009121",
    sku: "MED-AMX-500-50",
    category: "Medicamentos",
    subCategory: "Antibióticos Betalactámicos",
    imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=400&q=80",
    description: "Antibiótico bactericida de amplio espectro para infecciones respiratorias, otorrinolaringológicas y dentales bajo prescripción médica.",
    shortDescription: "Caja x 50 Cápsulas. Venta bajo estricta receta médica.",
    costPriceCOP: 16500,
    salePriceCOP: 24500,
    marginPercent: 32.6,
    currentStock: 12,
    minStock: 15, // Low stock trigger!
    maxStock: 80,
    lotNumber: "LOT-2025-X09",
    expiryDate: "2026-11-20", // Expiring soon trigger!
    physicalLocation: "Estante 1 - Nevera / Antibióticos",
    requiresPrescription: true,
    status: "ACTIVO",
    supplier: "Laboratorios Laproff S.A.",
    pharmaInfo: {
      principioActivo: "Amoxicilina",
      concentracion: "500 mg",
      formaFarmaceutica: "Cápsulas duras",
      laboratorio: "Laproff S.A.",
      registroSanitarioINVIMA: "INVIMA 2019M-000451-R4",
      indicaciones: "Infecciones bacterianas causadas por microorganismos sensibles.",
      contraindicaciones: "Alergia conocida a penicilinas o cefalosporinas.",
      precauciones: "Completar el tratamiento según indicación médica para evitar resistencia.",
      formaDeUso: "1 cápsula cada 8 horas con agua.",
      almacenamiento: "Conservar en lugar fresco y seco.",
    },
  },
  {
    id: "med-04",
    name: "Losartán Potásico 50 mg (Caja x 30 Tab)",
    genericName: "Losartán Potásico",
    barcode: "7702132007821",
    sku: "MED-LOS-050-30",
    category: "Medicamentos",
    subCategory: "Cardiovascular e Hipertensión",
    imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=400&q=80",
    description: "Antihipertensivo antagonista de los receptores de angiotensina II para el control de la presión arterial en adultos.",
    shortDescription: "Caja x 30 Tabletas. Control de tensión arterial.",
    costPriceCOP: 7500,
    salePriceCOP: 11900,
    marginPercent: 37.0,
    currentStock: 35,
    minStock: 15,
    maxStock: 120,
    lotNumber: "LOT-2026-C44",
    expiryDate: "2027-12-15",
    physicalLocation: "Estante 3 - Control Cardiovascular",
    requiresPrescription: true,
    status: "ACTIVO",
    supplier: "Genfar S.A.",
    pharmaInfo: {
      principioActivo: "Losartán Potásico",
      concentracion: "50 mg",
      formaFarmaceutica: "Tabletas recubiertas",
      laboratorio: "Genfar S.A.",
      registroSanitarioINVIMA: "INVIMA 2021M-003319-R1",
      indicaciones: "Tratamiento de la hipertensión arterial esencial y nefropatía diabética.",
      contraindicaciones: "Embarazo, hipersensibilidad al principio activo.",
      precauciones: "Monitoreo regular de potasio sérico y presión arterial.",
      formaDeUso: "Vía oral 1 tableta diaria preferiblemente en la mañana.",
      almacenamiento: "Almacenar a menos de 30°C.",
    },
  },
  {
    id: "med-05",
    name: "Omeprazol 20 mg (Caja x 30 Cápsulas)",
    genericName: "Omeprazol",
    barcode: "7702132009944",
    sku: "MED-OME-020-30",
    category: "Medicamentos",
    subCategory: "Salud Gastrointestinal y Antiácidos",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    description: "Inhibidor de la bomba de protones indicado para el tratamiento del reflujo gastroesofágico, gastritis y úlcera gástrica.",
    shortDescription: "Caja x 30 Cápsulas. Alivio del ardor estomacal y reflujo.",
    costPriceCOP: 6800,
    salePriceCOP: 11500,
    previousPriceCOP: 13900,
    marginPercent: 40.8,
    currentStock: 42,
    minStock: 15,
    maxStock: 150,
    lotNumber: "LOT-2026-OM3",
    expiryDate: "2027-11-20",
    physicalLocation: "Estante 1 - Digestivos",
    requiresPrescription: false,
    status: "ACTIVO",
    supplier: "Laboratorios MK / Tecnoquímicas",
    pharmaInfo: {
      principioActivo: "Omeprazol",
      concentracion: "20 mg por cápsula con microgránulos gastrorresistentes",
      formaFarmaceutica: "Cápsulas duras",
      laboratorio: "Laboratorios MK",
      registroSanitarioINVIMA: "INVIMA 2020M-0010923-R2",
      indicaciones: "Esofagitis por reflujo, gastritis erosiva y prevención de úlceras por medicamentos.",
      contraindicaciones: "Hipersensibilidad al omeprazol o a otros benzimidazoles.",
      precauciones: "Tomar preferiblemente en ayunas con medio vaso de agua sin masticar la cápsula.",
      formaDeUso: "1 cápsula en ayunas por la mañana.",
      almacenamiento: "Conservar a temperatura inferior a 30°C en su envase original.",
    },
  },
  {
    id: "med-06",
    name: "Loratadina 10 mg (Caja x 20 Tabletas)",
    genericName: "Loratadina",
    barcode: "7702132001188",
    sku: "MED-LOR-010-20",
    category: "Medicamentos",
    subCategory: "Antialérgicos y Respiratorios",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80",
    description: "Antihistamínico no sedante para el alivio rápido de síntomas de rinitis alérgica, estornudos, picazón nasal y urticaria.",
    shortDescription: "Caja x 20 Tabletas. Alivio de alergias sin producir somnolencia.",
    costPriceCOP: 4200,
    salePriceCOP: 7900,
    previousPriceCOP: 9500,
    marginPercent: 46.8,
    currentStock: 55,
    minStock: 20,
    maxStock: 120,
    lotNumber: "LOT-2026-LR1",
    expiryDate: "2028-02-10",
    physicalLocation: "Estante 2 - Respiratorios",
    requiresPrescription: false,
    status: "ACTIVO",
    supplier: "Genfar S.A.",
    pharmaInfo: {
      principioActivo: "Loratadina",
      concentracion: "10 mg",
      formaFarmaceutica: "Tabletas",
      laboratorio: "Genfar S.A.",
      registroSanitarioINVIMA: "INVIMA 2019M-0004381-R3",
      indicaciones: "Tratamiento de rinitis alérgica estacional o perenne y prurito por alergias.",
      contraindicaciones: "Hipersensibilidad a la loratadina o a los componentes de la fórmula.",
      precauciones: "Ajustar dosis en pacientes con daño hepático severo.",
      formaDeUso: "Adultos y niños mayores de 12 años: 1 tableta (10 mg) una vez al día.",
      almacenamiento: "Mantener en lugar seco y fresco a menos de 30°C.",
    },
  },
  {
    id: "med-07",
    name: "Naproxeno 500 mg (Caja x 20 Tabletas)",
    genericName: "Naproxeno Sódico",
    barcode: "7703345001222",
    sku: "MED-NAP-500-20",
    category: "Medicamentos",
    subCategory: "Analgésicos y Antiinflamatorios",
    imageUrl: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=400&q=80",
    description: "Alivio efectivo del dolor muscular, articular, cefaleas intensas y cólicos menstruales con acción prolongada.",
    shortDescription: "Caja x 20 Tabletas. Acción analgésica prolongada de hasta 12 horas.",
    costPriceCOP: 5500,
    salePriceCOP: 9800,
    previousPriceCOP: 12000,
    marginPercent: 43.8,
    currentStock: 30,
    minStock: 12,
    maxStock: 80,
    lotNumber: "LOT-2026-NP7",
    expiryDate: "2027-09-18",
    physicalLocation: "Estante 2 - Analgésicos",
    requiresPrescription: false,
    status: "ACTIVO",
    supplier: "Laboratorios Lafrancol",
    pharmaInfo: {
      principioActivo: "Naproxeno Sódico",
      concentracion: "550 mg (equivalente a 500 mg de naproxeno)",
      formaFarmaceutica: "Tabletas recubiertas",
      laboratorio: "Laboratorios Lafrancol S.A.S.",
      registroSanitarioINVIMA: "INVIMA 2021M-001211-R2",
      indicaciones: "Dolores osteomusculares, inflamación de tendones, dismenorrea primaria y migraña.",
      contraindicaciones: "Úlcera péptica activa o antecedentes de sangrado gastrointestinal.",
      precauciones: "Tomar con alimentos o leche para minimizar el malestar gástrico.",
      formaDeUso: "1 tableta cada 12 horas después de las comidas.",
      almacenamiento: "Conservar a menos de 30°C.",
    },
  },
  {
    id: "med-08",
    name: "Salbutamol 100 mcg Aerosol (Frasco x 200 Dosis)",
    genericName: "Salbutamol Sulfato",
    barcode: "7707890123456",
    sku: "MED-SAL-100-200",
    category: "Medicamentos",
    subCategory: "Respiratorios y Asma",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    description: "Broncodilatador de acción rápida para el alivio inmediato del broncoespasmo en asma bronquial y bronquitis crónica.",
    shortDescription: "Inhalador x 200 inhalaciones. Alivio inmediato del broncoespasmo.",
    costPriceCOP: 13500,
    salePriceCOP: 19800,
    marginPercent: 31.8,
    currentStock: 18,
    minStock: 10,
    maxStock: 60,
    lotNumber: "LOT-2026-SL5",
    expiryDate: "2027-10-30",
    physicalLocation: "Estante 3 - Inhaladores",
    requiresPrescription: true,
    status: "ACTIVO",
    supplier: "GlaxoSmithKline / Aspen Pharma",
    pharmaInfo: {
      principioActivo: "Salbutamol",
      concentracion: "100 mcg por disparo",
      formaFarmaceutica: "Aerosol para inhalación bucal",
      laboratorio: "GlaxoSmithKline",
      registroSanitarioINVIMA: "INVIMA 2022M-0001844-R4",
      indicaciones: "Manejo y prevención del broncoespasmo en pacientes con enfermedad obstructiva reversible de vías respiratorias.",
      contraindicaciones: "Hipersensibilidad al salbutamol o a los propelentes de la formulación.",
      precauciones: "Usar con espaciador aerocámara en niños o adultos mayores para optimizar la llegada pulmonar.",
      formaDeUso: "1 a 2 inhalaciones cada 6 a 8 horas según criterio y prescripción médica.",
      almacenamiento: "Almacenar a temperatura inferior a 30°C protegiendo de la luz solar directa.",
    },
  },
];

export const initialRetailProducts: RetailProductItem[] = [
  {
    id: "prod-3",
    name: "Suero Oral Electrolitos 500 ml (Manzana)",
    sku: "RET-SUE-500-MAN",
    barcode: "7701123456789",
    category: "Bienestar",
    brand: "Electrolit / Hidraplus",
    description: "Solución rehidratante oral con electrolitos esenciales para recuperación rápida de hidratación por deshidratación o actividad física.",
    shortInfo: "Botella 500 ml. Hidratación equilibrada sabor manzana.",
    imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&q=80",
    priceCOP: 8900,
    promoPriceCOP: 7900,
    currentStock: 62,
    minStock: 25,
    weightGrams: 550,
    status: "ACTIVO",
    tags: ["Hidratación", "Bienestar", "Electrolitos"],
  },
  {
    id: "prod-4",
    name: "Alcohol Antiséptico 70% 1000 ml",
    sku: "RET-ALC-1000-70",
    barcode: "7709988776655",
    category: "Cuidado de la Salud",
    brand: "FarmaBoy Esenciales",
    description: "Alcohol antiséptico al 70% para desinfección de superficies, elementos del botiquín e higiene de manos.",
    shortInfo: "Botella 1000 ml. Desinfección efectiva de amplio espectro.",
    imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80",
    priceCOP: 14500,
    currentStock: 40,
    minStock: 15,
    weightGrams: 1000,
    status: "ACTIVO",
    tags: ["Antiséptico", "Botiquín", "Desinfección"],
  },
  {
    id: "prod-5",
    name: "Bloqueador Solar SPF 50+ Facial 60g",
    sku: "RET-BLO-060-SPF",
    barcode: "7705544332211",
    category: "Cuidado Personal",
    brand: "DermoCare Boyacá",
    description: "Protector solar facial de textura toque seco de rápida absorción con filtros UVA y UVB de amplio espectro contra fotoenvejecimiento.",
    shortInfo: "Tubo 60g. Protección alta toque seco para piel boyacense.",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
    priceCOP: 58000,
    promoPriceCOP: 49900,
    currentStock: 18,
    minStock: 10,
    weightGrams: 80,
    status: "ACTIVO",
    tags: ["Dermocosmética", "Protección Solar", "Facial"],
  },
  {
    id: "prod-6",
    name: "Tensiómetro Digital Automático de Brazo",
    sku: "RET-TEN-DIG-ARM",
    barcode: "7704433221100",
    category: "Equipos y Dispositivos",
    brand: "Omron Healthcare",
    description: "Monitor de presión arterial automático para brazo con memoria digital para 60 lecturas, detección de latido irregular y brazalete ergonómico.",
    shortInfo: "Monitor digital con brazalete universal y memoria para 60 tomas.",
    imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80",
    priceCOP: 145000,
    currentStock: 7,
    minStock: 5,
    weightGrams: 450,
    status: "ACTIVO",
    tags: ["Dispositivo Médico", "Monitoreo", "Tensión Arterial"],
  },
  {
    id: "prod-07",
    name: "CeraVe Gel Limpiador Espumoso 473 ml",
    sku: "RET-CRV-ESP-473",
    barcode: "7708899001122",
    category: "Dermocosmética",
    brand: "CeraVe",
    description: "Gel espumoso dermatológico formulado con 3 ceramidas esenciales y niacinamida para limpiar profundamente sin alterar la barrera protectora de la piel.",
    shortInfo: "Frasco 473 ml con dispensador. Para piel normal a grasa.",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
    priceCOP: 84900,
    promoPriceCOP: 72900,
    currentStock: 22,
    minStock: 8,
    weightGrams: 520,
    status: "ACTIVO",
    tags: ["Dermocosmética", "Limpiador", "Piel Grasa", "Ceramidas"],
  },
  {
    id: "prod-08",
    name: "La Roche-Posay Anthelios UVMune 400 SPF 50+ 50ml",
    sku: "RET-LRP-ANT-050",
    barcode: "7707788992233",
    category: "Dermocosmética",
    brand: "La Roche-Posay",
    description: "Máxima protección solar dermatológica contra los rayos UVA ultra-largos. Textura fluida invisible, resistente al agua y sudor, no pica en los ojos.",
    shortInfo: "Frasco 50 ml fluido invisible toque seco con filtro Mexoryl 400.",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80",
    priceCOP: 119000,
    promoPriceCOP: 99900,
    currentStock: 15,
    minStock: 5,
    weightGrams: 85,
    status: "ACTIVO",
    tags: ["Dermocosmética", "Protector Solar", "SPF50", "Anthelios"],
  },
  {
    id: "prod-09",
    name: "Vitamina C 500 mg + Zinc (Gomitas Frasco x 60)",
    sku: "RET-VIT-C-ZNC-60",
    barcode: "7706677883344",
    category: "Vitaminas y Suplementos",
    brand: "MK Nutrición",
    description: "Deliciosas gomitas sabor naranja enriquecidas con Vitamina C y Zinc para el fortalecimiento del sistema inmunológico en adultos y jóvenes.",
    shortInfo: "Frasco x 60 gomitas masticables sabor cítrico. Refuerzo de defensas.",
    imageUrl: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=400&q=80",
    priceCOP: 38900,
    promoPriceCOP: 32500,
    currentStock: 45,
    minStock: 15,
    weightGrams: 280,
    status: "ACTIVO",
    tags: ["Vitaminas", "Defensas", "Inmunidad", "Zinc"],
  },
  {
    id: "prod-10",
    name: "Ensure Advance Polvo Vainilla 850g",
    sku: "RET-ENS-ADV-850",
    barcode: "7705566774455",
    category: "Vitaminas y Suplementos",
    brand: "Abbott",
    description: "Nutrición especializada completa y balanceada con CaHMB, proteína de alta calidad y 28 vitaminas y minerales para mantener masa muscular y fuerza.",
    shortInfo: "Lata 850g sabor vainilla. Nutrición clínica para adultos.",
    imageUrl: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=400&q=80",
    priceCOP: 114500,
    promoPriceCOP: 98900,
    currentStock: 28,
    minStock: 10,
    weightGrams: 950,
    status: "ACTIVO",
    tags: ["Nutrición", "Adulto Mayor", "Proteína", "Ensure"],
  },
  {
    id: "prod-11",
    name: "Pañales Huggies Natural Care Etapa 3 (Paquete x 50)",
    sku: "RET-HUG-ET3-050",
    barcode: "7704455665566",
    category: "Bebés y Maternidad",
    brand: "Huggies",
    description: "Pañales con tecnología de máxima absorción y suavidad tipo algodón. Cuidado delicado para la piel del bebé con barreras antifugas reforzadas.",
    shortInfo: "Paquete x 50 pañales unisex etapa 3 (7 a 11 kg).",
    imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=400&q=80",
    priceCOP: 54900,
    promoPriceCOP: 46900,
    currentStock: 38,
    minStock: 12,
    weightGrams: 1200,
    status: "ACTIVO",
    tags: ["Bebés", "Pañales", "Huggies", "Maternidad"],
  },
  {
    id: "prod-12",
    name: "Crema Antipañalitis No. 4 Medicada 110g",
    sku: "RET-CR4-MED-110",
    barcode: "7703344556677",
    category: "Bebés y Maternidad",
    brand: "Sanofi",
    description: "Pomada protectora con óxido de zinc al 40% para la prevención y alivio rápido de la dermatitis del pañal en lactantes e infantes.",
    shortInfo: "Tubo 110g con óxido de zinc de alta concentración.",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
    priceCOP: 26500,
    currentStock: 40,
    minStock: 15,
    weightGrams: 140,
    status: "ACTIVO",
    tags: ["Bebés", "Antipañalitis", "Cuidado Infantil", "Sanofi"],
  },
  {
    id: "prod-13",
    name: "Glucómetro Accu-Chek Instant Kit Completo",
    sku: "RET-ACC-INS-KIT",
    barcode: "7702233447788",
    category: "Dispositivos Médicos",
    brand: "Roche Diabetes Care",
    description: "Medidor de glucosa en sangre instantáneo con indicador de rango por colores, conectividad Bluetooth, incluye 10 tiras reactivas y puncionador.",
    shortInfo: "Kit medidor con 10 tiras reactivas y lancetas. Precisión clínica Roche.",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=400&q=80",
    priceCOP: 89000,
    promoPriceCOP: 79900,
    currentStock: 12,
    minStock: 5,
    weightGrams: 320,
    status: "ACTIVO",
    tags: ["Dispositivos Médicos", "Diabetes", "Glucómetro", "Accu-Chek"],
  },
  {
    id: "prod-14",
    name: "Termómetro Digital Infrarrojo Sin Contacto",
    sku: "RET-TER-INF-001",
    barcode: "7701122338899",
    category: "Dispositivos Médicos",
    brand: "Omron Healthcare",
    description: "Termómetro infrarrojo para medición rápida en frente a distancia de 1 a 3 cm. Lectura en 1 segundo con alarma sonora de fiebre y pantalla iluminada.",
    shortInfo: "Medición rápida en 1 segundo sin contacto. Alarma de fiebre.",
    imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80",
    priceCOP: 68000,
    currentStock: 16,
    minStock: 6,
    weightGrams: 180,
    status: "ACTIVO",
    tags: ["Dispositivos Médicos", "Termómetro", "Fiebre", "Infrarrojo"],
  },
  {
    id: "prod-15",
    name: "Enjuague Bucal Colgate PerioGard 250 ml Sin Alcohol",
    sku: "RET-COL-PER-250",
    barcode: "7709900112233",
    category: "Higiene y Salud Oral",
    brand: "Colgate",
    description: "Solución antibacteriana con Gluconato de Clorhexidina al 0.12% para el control efectivo de la placa bacteriana, gingivitis y sangrado de encías.",
    shortInfo: "Frasco 250 ml con clorhexidina 0.12% para encías saludables.",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
    priceCOP: 33000,
    promoPriceCOP: 28900,
    currentStock: 25,
    minStock: 10,
    weightGrams: 300,
    status: "ACTIVO",
    tags: ["Higiene", "Salud Oral", "Encías", "Colgate"],
  },
  {
    id: "prod-16",
    name: "Preservativos Durex Invisible Ultra Delgado (Caja x 6)",
    sku: "RET-DUR-INV-006",
    barcode: "7708877665544",
    category: "Salud Sexual",
    brand: "Durex",
    description: "Los preservativos más delgados desarrollados por Durex para maximizar la sensibilidad y el placer sin comprometer la seguridad ni la protección.",
    shortInfo: "Caja x 6 condones de látex ultra delgado con lubricación premium.",
    imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80",
    priceCOP: 24500,
    promoPriceCOP: 19900,
    currentStock: 35,
    minStock: 10,
    weightGrams: 65,
    status: "ACTIVO",
    tags: ["Salud Sexual", "Preservativos", "Durex", "Bienestar Íntimo"],
  },
  {
    id: "prod-17",
    name: "Gel Lubricante Íntimo K-Y Base Agua 100g",
    sku: "RET-KYG-LUB-100",
    barcode: "7707766554433",
    category: "Salud Sexual",
    brand: "K-Y",
    description: "Gel lubricante a base de agua, transparente, no graso e inodoro. Compatible con preservativos de látex para alivio de la resequedad íntima.",
    shortInfo: "Tubo 100g a base de agua. Suavidad y confort íntimo.",
    imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
    priceCOP: 22000,
    currentStock: 29,
    minStock: 8,
    weightGrams: 120,
    status: "ACTIVO",
    tags: ["Salud Sexual", "Lubricante", "K-Y", "Bienestar"],
  },
  {
    id: "prod-18",
    name: "Agua Micelar Bioderma Sensibio H2O 500 ml",
    sku: "RET-BIO-SEN-500",
    barcode: "7706655443322",
    category: "Belleza y Cosmética",
    brand: "Bioderma",
    description: "Agua micelar dermatológica de culto para piel sensible. Limpia y desmaquilla rostro y ojos en un solo paso respetando el film hidrolipídico.",
    shortInfo: "Botella 500 ml para piel sensible y reactiva. No requiere enjuague.",
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80",
    priceCOP: 96000,
    promoPriceCOP: 79900,
    currentStock: 14,
    minStock: 6,
    weightGrams: 550,
    status: "ACTIVO",
    tags: ["Belleza", "Dermocosmética", "Bioderma", "Desmaquillante"],
  },
  {
    id: "prod-19",
    name: "Shampoo Anticaspa Medicasp Ketoconazol 130 ml",
    sku: "RET-MED-SHA-130",
    barcode: "7705544332219",
    category: "Cuidado Personal",
    brand: "Medicasp",
    description: "Tratamiento clínicamente comprobado contra el hongo causante de la caspa persistente. Alivia el enrojecimiento, ardor y descamación del cuero cabelludo.",
    shortInfo: "Frasco 130 ml con ketoconazol al 1%. Alivio rápido de la caspa.",
    imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&q=80",
    priceCOP: 36900,
    currentStock: 20,
    minStock: 8,
    weightGrams: 160,
    status: "ACTIVO",
    tags: ["Cuidado Personal", "Capilar", "Ketoconazol", "Anticaspa"],
  },
];

export const initialInventoryMovements: InventoryMovement[] = [
  {
    id: "mov-101",
    productId: "med-01",
    productName: "Acetaminofén 500 mg (Caja x 100 Tab)",
    type: "ENTRADA",
    quantity: 50,
    previousStock: 0,
    newStock: 50,
    reason: "Compra Factura Proveedor Genfar #88210",
    lotNumber: "LOT-2026-A88",
    expiryDate: "2027-08-30",
    user: "Dra. Carolina Vargas",
    date: "2026-09-01 10:15",
    costUnitCOP: 8200,
  },
  {
    id: "mov-102",
    productId: "med-01",
    productName: "Acetaminofén 500 mg (Caja x 100 Tab)",
    type: "SALIDA",
    quantity: 2,
    previousStock: 50,
    newStock: 48,
    reason: "Venta Pedido Online #FB-10842",
    user: "Sistema Wompi",
    date: "2026-09-04 14:30",
  },
  {
    id: "mov-103",
    productId: "med-03",
    productName: "Amoxicilina 500 mg (Caja x 50 Cápsulas)",
    type: "AJUSTE",
    quantity: -3,
    previousStock: 15,
    newStock: 12,
    reason: "Avería de empaque durante inspección de calidad",
    user: "Dr. Roberto Salamanca",
    date: "2026-09-05 16:20",
  },
];

export const initialAdminOrders: AdminOrder[] = [
  {
    id: "FB-11024",
    customerName: "Carlos Rodríguez Cárdenas",
    customerEmail: "carlos.rodriguez@email.com",
    customerPhone: "312 456 7890",
    customerDocument: "CC 1049628391",
    date: "2026-09-07 15:40",
    status: "EN_CAMINO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "med-01", name: "Acetaminofén 500 mg (Caja x 100 Tab)", quantity: 2, priceCOP: 12500, imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-3", name: "Suero Oral Electrolitos 500 ml (Manzana)", quantity: 1, priceCOP: 8900, imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 33900,
    shippingCOP: 5000,
    discountCOP: 0,
    totalCOP: 38900,
    paymentMethod: "Wompi PSE Bancolombia",
    deliveryCity: "Duitama",
    deliveryAddress: "Carrera 16 # 12-40 Apto 302",
    deliveryNotes: "Timbrar en el apartamento 302. Domicilio urgente.",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-07 15:40", note: "Orden recibida vía e-commerce" },
      { status: "CONFIRMADO", timestamp: "2026-09-07 15:42", note: "Pago confirmado con Wompi" },
      { status: "PREPARANDO", timestamp: "2026-09-07 16:00", note: "Lote verificado y empacado" },
      { status: "EN_CAMINO", timestamp: "2026-09-07 16:25", note: "Mensajero asignado con ruta Duitama Centro" },
    ],
  },
  {
    id: "FB-11025",
    customerName: "Mariana Fonseca",
    customerEmail: "mariana.fonseca@email.com",
    customerPhone: "310 889 7711",
    customerDocument: "CC 40389102",
    date: "2026-09-07 16:15",
    status: "LISTO_RECOGER",
    deliveryMethod: "PUNTO_RECOGIDA",
    pickupPointId: "pickup-duitama-centro",
    pickupPointName: "Sede Principal Farmaboy - Duitama Centro",
    items: [
      { id: "prod-11", name: "Pañales Huggies Natural Care Etapa 3 (Paquete x 50)", quantity: 1, priceCOP: 46900, imageUrl: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 46900,
    shippingCOP: 0,
    discountCOP: 0,
    totalCOP: 46900,
    paymentMethod: "Wompi Tarjeta de Crédito (Visa 9210)",
    deliveryCity: "Duitama",
    deliveryAddress: "Sede Principal: Carrera 16 # 15-20, Centro, Duitama",
    deliveryNotes: "Pasa a recoger el esposo en la tarde",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-07 16:15", note: "Orden recibida para recogida en punto" },
      { status: "CONFIRMADO", timestamp: "2026-09-07 16:17", note: "Pago procesado satisfactoriamente" },
      { status: "LISTO_RECOGER", timestamp: "2026-09-07 16:35", note: "Empacado en módulo de entregas Farmaboy Centro" },
    ],
  },
  {
    id: "FB-11026",
    customerName: "Jorge Eliécer Barón",
    customerEmail: "jorge.baron@boyaca.gov.co",
    customerPhone: "314 200 4567",
    customerDocument: "CC 74182930",
    date: "2026-09-07 17:30",
    status: "PREPARANDO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "prod-4", name: "Alcohol Antiséptico 70% 1000 ml", quantity: 2, priceCOP: 14500, imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-12", name: "Crema Antipañalitis No. 4 Medicada 110g", quantity: 1, priceCOP: 26500, imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 55500,
    shippingCOP: 5000,
    discountCOP: 0,
    totalCOP: 60500,
    paymentMethod: "Wompi Nequi",
    deliveryCity: "Duitama",
    deliveryAddress: "Calle 18 # 14-22 Barrio La Gruta",
    deliveryNotes: "Casa blanca de dos pisos",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-07 17:30", note: "Orden registrada" },
      { status: "CONFIRMADO", timestamp: "2026-09-07 17:32", note: "Pago recibido vía Nequi" },
      { status: "PREPARANDO", timestamp: "2026-09-07 17:40", note: "En alistamiento por auxiliar de farmacia" },
    ],
  },
  {
    id: "FB-11027",
    customerName: "Andrea Gómez Prieto",
    customerEmail: "andrea.gomez@gmail.com",
    customerPhone: "311 987 6543",
    customerDocument: "CC 1052384920",
    date: "2026-09-07 18:05",
    status: "NUEVO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "prod-5", name: "Bloqueador Solar SPF 50+ Facial 60g", quantity: 1, priceCOP: 49900, imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-16", name: "Preservativos Durex Invisible Ultra Delgado (Caja x 6)", quantity: 1, priceCOP: 19900, imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 69800,
    shippingCOP: 6500,
    discountCOP: 0,
    totalCOP: 76300,
    paymentMethod: "Wompi Daviplata",
    deliveryCity: "Paipa",
    deliveryAddress: "Carrera 20 # 25-10 Barrio Corinto",
    deliveryNotes: "Llamar al llegar",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-07 18:05", note: "Orden ingresada pendiente de confirmación de despacho" },
    ],
  },
  {
    id: "FB-10998",
    customerName: "Lucía Moreno Vargas",
    customerEmail: "lucia.moreno@outlook.com",
    customerPhone: "313 555 4321",
    customerDocument: "CC 23891045",
    date: "2026-09-06 11:20",
    status: "ENTREGADO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "prod-13", name: "Glucómetro Accu-Chek Instant Kit Completo", quantity: 1, priceCOP: 79900, imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 79900,
    shippingCOP: 0,
    discountCOP: 0,
    totalCOP: 79900,
    paymentMethod: "Wompi PSE Bancolombia",
    deliveryCity: "Duitama",
    deliveryAddress: "Carrera 14 # 9-18 Interior 201",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-06 11:20", note: "Orden recibida" },
      { status: "CONFIRMADO", timestamp: "2026-09-06 11:22", note: "Pago verificado" },
      { status: "ENVIADO", timestamp: "2026-09-06 12:15", note: "Despachado en moto" },
      { status: "ENTREGADO", timestamp: "2026-09-06 13:00", note: "Entregado a la titular" },
    ],
  },
  {
    id: "FB-10999",
    customerName: "Pedro Salamanca Niño",
    customerEmail: "pedro.salamanca@gmail.com",
    customerPhone: "320 444 8899",
    customerDocument: "CC 1054321980",
    date: "2026-09-06 16:45",
    status: "RECOGIDO",
    deliveryMethod: "PUNTO_RECOGIDA",
    pickupPointId: "pickup-duitama-centro",
    pickupPointName: "Sede Principal Farmaboy - Duitama Centro",
    items: [
      { id: "prod-16", name: "Preservativos Durex Invisible Ultra Delgado (Caja x 6)", quantity: 1, priceCOP: 19900, imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80" },
      { id: "med-01", name: "Acetaminofén 500 mg (Caja x 100 Tab)", quantity: 1, priceCOP: 12500, imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 32400,
    shippingCOP: 0,
    discountCOP: 0,
    totalCOP: 32400,
    paymentMethod: "Wompi Nequi",
    deliveryCity: "Duitama",
    deliveryAddress: "Sede Principal Duitama",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-06 16:45", note: "Orden recibida" },
      { status: "LISTO_RECOGER", timestamp: "2026-09-06 17:05", note: "Listo en ventanilla" },
      { status: "RECOGIDO", timestamp: "2026-09-06 18:20", note: "Retirado con cédula por el cliente" },
    ],
  },
  {
    id: "FB-10842",
    customerName: "Carlos Rodríguez Cárdenas",
    customerEmail: "carlos.rodriguez@email.com",
    customerPhone: "312 456 7890",
    customerDocument: "CC 1049628391",
    date: "2026-09-04 14:30",
    status: "ENTREGADO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "med-01", name: "Acetaminofén 500 mg (Caja x 100 Tab)", quantity: 2, priceCOP: 12500, imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-3", name: "Suero Oral Electrolitos 500 ml (Manzana)", quantity: 4, priceCOP: 8900, imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 60600,
    shippingCOP: 7000,
    discountCOP: 5000,
    totalCOP: 62600,
    paymentMethod: "Wompi Bancolombia Débito (4821)",
    deliveryCity: "Tunja",
    deliveryAddress: "Carrera 2 Este # 58-30 Torre 3 Apto 502",
    deliveryNotes: "Dejar en portería si no contestan citófono",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-04 14:30", note: "Orden recibida vía e-commerce" },
      { status: "CONFIRMADO", timestamp: "2026-09-04 14:32", note: "Pago aprobado con Wompi" },
      { status: "PREPARANDO", timestamp: "2026-09-04 15:00", note: "Empaque y verificación de lote por regente" },
      { status: "EN_CAMINO", timestamp: "2026-09-04 16:10", note: "En ruta con domiciliario express Tunja" },
      { status: "ENTREGADO", timestamp: "2026-09-04 17:15", note: "Entregado a satisfacción" },
    ],
  },
  {
    id: "FB-10755",
    customerName: "Farmacia Comunitaria Sogamoso",
    customerEmail: "pedidos@farmaciacomunitaria.com",
    customerPhone: "318 222 3344",
    customerDocument: "NIT 900.552.190-3",
    date: "2026-09-02 09:10",
    status: "ENTREGADO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "med-01", name: "Acetaminofén 500 mg (Caja x 100 Tab)", quantity: 15, priceCOP: 12500, imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-4", name: "Alcohol Antiséptico 70% 1000 ml", quantity: 10, priceCOP: 14500, imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 332500,
    shippingCOP: 0,
    discountCOP: 0,
    totalCOP: 332500,
    paymentMethod: "Wompi PSE Bancolombia",
    deliveryCity: "Sogamoso",
    deliveryAddress: "Calle 11 # 12-30 Centro Sogamoso",
    trackingHistory: [
      { status: "ENTREGADO", timestamp: "2026-09-02 14:00", note: "Entregado en droguería aliada" },
    ],
  },
  {
    id: "FB-09941",
    customerName: "Carlos Rodríguez Cárdenas",
    customerEmail: "carlos.rodriguez@email.com",
    customerPhone: "312 456 7890",
    customerDocument: "CC 1049628391",
    date: "2026-08-20 10:15",
    status: "ENTREGADO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "prod-4", name: "Alcohol Antiséptico 70% 1000 ml", quantity: 2, priceCOP: 14500, imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80" },
      { id: "med-02", name: "Ibuprofeno 800 mg (Caja x 30 Tab)", quantity: 1, priceCOP: 16800, imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80" },
      { id: "prod-6", name: "Tensiómetro Digital Automático de Brazo", quantity: 1, priceCOP: 145000, imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 190800,
    shippingCOP: 0,
    discountCOP: 0,
    totalCOP: 190800,
    paymentMethod: "Wompi PSE Bancolombia",
    deliveryCity: "Tunja",
    deliveryAddress: "Carrera 2 Este # 58-30 Torre 3 Apto 502",
    trackingHistory: [
      { status: "ENTREGADO", timestamp: "2026-08-20 12:30", note: "Entregado a satisfacción al cliente" },
    ],
  },
  {
    id: "FB-08712",
    customerName: "Mariana Fonseca",
    customerEmail: "mariana.fonseca@email.com",
    customerPhone: "310 889 7711",
    customerDocument: "CC 40389102",
    date: "2026-09-05 18:20",
    status: "CONFIRMADO",
    deliveryMethod: "DOMICILIO",
    items: [
      { id: "prod-5", name: "Bloqueador Solar SPF 50+ Facial 60g", quantity: 2, priceCOP: 49900, imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80" },
    ],
    subtotalCOP: 99800,
    shippingCOP: 0,
    discountCOP: 10000,
    totalCOP: 89800,
    paymentMethod: "Wompi Tarjeta Visa",
    deliveryCity: "Duitama",
    deliveryAddress: "Avenida de las Américas # 14-30",
    trackingHistory: [
      { status: "NUEVO", timestamp: "2026-09-05 18:20", note: "Orden recibida" },
      { status: "CONFIRMADO", timestamp: "2026-09-05 18:22", note: "Pago validado" },
    ],
  },
];

export const initialCustomers: CustomerCRM[] = [
  {
    id: "cust-01",
    name: "Carlos",
    lastName: "Rodríguez Cárdenas",
    email: "carlos.rodriguez@email.com",
    phone: "312 456 7890",
    documentType: "CC",
    documentNumber: "1049628391",
    city: "Tunja",
    address: "Carrera 2 Este # 58-30 Torre 3 Apto 502",
    registrationDate: "2025-01-15",
    lastLoginDate: "Hoy 14:15",
    totalOrders: 4,
    totalSpentCOP: 449400,
    averageTicketCOP: 112350,
    lastOrderDate: "2026-09-04",
    segment: "VIP",
    notes: "Cliente recurrente con suscripción de Acetaminofén y entregas en La Meseta.",
    lifetimeDiscountPercentage: 10,
    lifetimeDiscountReason: "Tratamiento Hipertensión / Cliente VIP Crónico",
    isLifetimeDiscountActive: true,
  },
  {
    id: "cust-02",
    name: "Mariana",
    lastName: "Fonseca",
    email: "mariana.fonseca@email.com",
    phone: "310 889 7711",
    documentType: "CC",
    documentNumber: "40389102",
    city: "Duitama",
    address: "Avenida de las Américas # 14-30",
    registrationDate: "2025-06-20",
    lastLoginDate: "Ayer 18:20",
    totalOrders: 2,
    totalSpentCOP: 145800,
    averageTicketCOP: 72900,
    lastOrderDate: "2026-09-05",
    segment: "FRECUENTE",
    notes: "Paciente frecuente de Duitama, plan maternidad y cuidado infantil.",
    lifetimeDiscountPercentage: 5,
    lifetimeDiscountReason: "Plan Maternidad & Cuidado Infantil",
    isLifetimeDiscountActive: true,
  },
  {
    id: "cust-03",
    name: "Clínica Los Andes Boyacá",
    lastName: "(Cuenta Institucional)",
    email: "compras@clinicalosandesboyaca.com",
    phone: "315 777 9900",
    documentType: "NIT",
    documentNumber: "900.871.229-1",
    city: "Tunja",
    address: "Calle 24 # 9-45",
    registrationDate: "2024-11-10",
    lastLoginDate: "02 Sep 09:30",
    totalOrders: 14,
    totalSpentCOP: 18450000,
    averageTicketCOP: 1317857,
    lastOrderDate: "2026-08-28",
    segment: "MAYORISTA",
    notes: "Convenio de suministro para medicamentos e insumos hospitalarios.",
    lifetimeDiscountPercentage: 18,
    lifetimeDiscountReason: "Convenio Institucional Hospitalario Boyacá",
    isLifetimeDiscountActive: true,
  },
];

export const initialPromotions: PromotionRule[] = [
  {
    id: "promo-01",
    title: "15% de Descuento Boyacá Saludable",
    code: "BOYACA15",
    type: "PORCENTAJE",
    value: 15,
    minPurchaseCOP: 50000,
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    maxUsesTotal: 500,
    usedCount: 42,
    maxUsesPerCustomer: 2,
    isActive: true,
  },
  {
    id: "promo-02",
    title: "$10.000 COP de Descuento FarmaFiesta",
    code: "FARMAFIESTA",
    type: "FIJO",
    value: 10000,
    minPurchaseCOP: 80000,
    startDate: "2026-09-01",
    endDate: "2026-10-15",
    maxUsesTotal: 300,
    usedCount: 18,
    maxUsesPerCustomer: 1,
    isActive: true,
  },
];

export const initialBanners: BannerItem[] = [
  {
    id: "ban-01",
    title: "Medicamentos, Bienestar y Cuidado en Boyacá",
    subtitle: "Pide en línea con entrega rápida en Tunja, Duitama y Sogamoso. Pagos seguros con Wompi Bancolombia.",
    badge: "Droguería Digital de Confianza",
    imageUrl: "/images/fachada-farmaboy.jpg",
    linkUrl: "/medicamentos",
    buttonText: "Ver Catálogo de Medicamentos",
    placement: "HERO_PRINCIPAL",
    isActive: true,
    order: 1,
  },
  {
    id: "ban-02",
    title: "Botiquín & Primeros Auxilios para tu Hogar",
    subtitle: "Asegura la salud de tu familia con productos esenciales y asesoría farmacéutica certificada.",
    badge: "Oferta Especial",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    linkUrl: "/medicamentos?cat=primeros-auxilios",
    buttonText: "Explorar Botiquín",
    placement: "HERO_PRINCIPAL",
    isActive: true,
    order: 2,
  },
];

export const initialSiteDesign: SiteDesignConfig = {
  siteName: "Farmaboy",
  tagline: "Tu farmacia de confianza en Boyacá",
  colors: {
    primary: "#00A86B",
    primaryDark: "#008755",
    primaryLight: "#10B981",
    secondary: "#00A896",
    accent: "#10B981",
    promo: "#F59E0B",
    surface: "#FFFFFF",
    background: "#FFFFFF",
    text: "#0F172A",
  },
  fontFamily: "Inter",
  homepageSections: {
    hero: true,
    categories: true,
    featuredProducts: true,
    dealsBanners: true,
    pharmacyServices: true,
    muchMore: true,
    transportSection: true,
    b2bSection: true,
    trustSection: true,
    faqSection: true,
    contactCta: true,
  },
  headerNotice: "Farmacia con despachos diarios a toda Boyacá",
  footerDescription: "Empresa de servicios farmacéuticos y asistenciales en Boyacá, Colombia. Comprometidos con el bienestar integral de nuestra comunidad.",
};

export const initialSeo: SeoConfig = {
  siteTitleDefault: "Farmaboy | Tu farmacia de confianza en Boyacá",
  siteDescriptionDefault: "Farmacia y droguería moderna en Boyacá, Colombia. Medicamentos, cuidado personal, bienestar, insumos hospitalarios y transporte asistencial. Pagos seguros Wompi.",
  keywords: ["farmacia en Boyacá", "medicamentos en Tunja", "droguería Duitama", "insumos hospitalarios Sogamoso", "comprar medicamentos wompi"],
  canonicalBase: "https://farmaboy.com.co",
  ogImageUrl: "https://images.unsplash.com/photo-1586015555751-63c2999e32a4?q=80&w=1200",
  indexEnabled: true,
  schemaType: "Pharmacy",
};

export const initialBlogPosts: BlogPost[] = [
  {
    id: "post-01",
    title: "Consejos clave para conservar tus medicamentos en clima frío de Boyacá",
    slug: "conservacion-medicamentos-clima-frio-boyaca",
    excerpt: "Aprende a proteger tus medicamentos de la humedad y bajas temperaturas sin alterar su efectividad química.",
    content: "La altitud y el clima de ciudades como Tunja, Duitama y Sogamoso presentan variaciones de temperatura y humedad que pueden afectar la estabilidad de ciertos jarabes y suspensiones...",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
    author: "Dra. Carolina Vargas (Q.F.)",
    category: "Salud y Bienestar",
    tags: ["Consejos Farmacéuticos", "Autocuidado", "Boyacá"],
    publishDate: "2026-08-25",
    isPublished: true,
  },
  {
    id: "post-02",
    title: "Guía para armar el botiquín de emergencia en el hogar y en empresas",
    slug: "guia-botiquin-emergencia-hogar-empresas",
    excerpt: "Los 10 elementos que nunca deben faltar para atender quemaduras, cortes o malestares cotidianos.",
    content: "Contar con un botiquín completo y al día es una de las medidas preventivas más importantes tanto para el hogar como para los centros de trabajo en Boyacá...",
    imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=800&q=80",
    author: "Dr. Roberto Salamanca",
    category: "Primeros Auxilios",
    tags: ["Botiquín", "Seguridad", "Empresas"],
    publishDate: "2026-09-02",
    isPublished: true,
  },
];

export const initialStoreSettings: CommercialStoreSettings = {
  legalName: "FARMABOY INTEGRALES DE SERVICIOS EN SALUD S.A.S.",
  brandName: "FARMABOY",
  nit: "902.054.200-0",
  phone: "+573223863977",
  phoneDisplay: "+57 322 386 3977",
  whatsapp: "573223863977",
  whatsappDisplay: "+57 322 386 3977",
  emailGeneral: "info@farmaboy.com",
  addressPrincipal: "Avenida Circunvalar No. 10 - 256, Duitama",
  city: "Duitama",
  department: "Boyacá",
  operatingHours: "Lunes a Sábado: 7:00 am - 9:00 pm | Domingos y Festivos: 8:00 am - 7:00 pm",
  currency: "COP",
  freeShippingThresholdCOP: 70000,
  standardShippingCostCOP: 5000,
  deliveryZones: [
    { city: "Duitama (Casco Urbano)", feeCOP: 5000, estimatedTime: "30 a 60 min", isActive: true },
    { city: "Duitama (Rural / Veredas)", feeCOP: 9000, estimatedTime: "2 a 3 horas", isActive: true },
    { city: "Paipa", feeCOP: 6500, estimatedTime: "60 a 90 min", isActive: true },
    { city: "Sogamoso", feeCOP: 8000, estimatedTime: "Ruta diaria (2 a 4 horas)", isActive: true },
    { city: "Tunja", feeCOP: 7000, estimatedTime: "Mismo día", isActive: true },
    { city: "Nobsa / Tibasosa", feeCOP: 7500, estimatedTime: "1 a 2 horas", isActive: true },
  ],
};

export const initialIntegrations: IntegrationsConfig = {
  wompiPublicKey: "pub_test_PLACEHOLDER_FARMABOY",
  wompiEnvironment: "test",
  googleAnalyticsId: "G-FARMABOY01",
  metaPixelId: "PIXEL-FB-9988",
  googleTagManagerId: "GTM-FMB2026",
  dianElectronicBillingActive: true,
};

export const initialActivityLogs: ActivityLog[] = [
  {
    id: "act-01",
    user: "Dr. Roberto Salamanca",
    role: "SUPER_ADMIN",
    action: "Modificación de Tarifa de Envío",
    entity: "Duitama Urbana",
    details: "Tarifa fijada a $5.000 COP para despacho local",
    timestamp: "Hoy 14:15",
  },
  {
    id: "act-02",
    user: "Dra. Carolina Vargas",
    role: "FARMACEUTICO",
    action: "Entrada de Inventario",
    entity: "Amoxicilina 500 mg",
    details: "Ingreso de lote LOT-2025-X09 (+50 unidades)",
    timestamp: "Ayer 17:30",
  },
  {
    id: "act-03",
    user: "Santiago Gómez",
    role: "VENTAS",
    action: "Despacho de Pedido",
    entity: "Pedido #FB-11024",
    details: "Estado cambiado a EN_CAMINO para Duitama Centro",
    timestamp: "Hoy 16:25",
  },
];

export const initialDeliveryRates: DeliveryRate[] = [
  {
    id: "rate-duitama-urbana",
    department: "Boyacá",
    municipality: "Duitama",
    zone: "Casco Urbano Duitama",
    rateCOP: 5000,
    minOrderCOP: 20000,
    freeShippingFromCOP: 70000,
    estimatedTime: "30 a 60 min",
    isActive: true,
  },
  {
    id: "rate-duitama-rural",
    department: "Boyacá",
    municipality: "Duitama",
    zone: "Veredas y Corregimientos (Surba, La Trinidad, Higueras)",
    rateCOP: 9000,
    minOrderCOP: 30000,
    freeShippingFromCOP: 120000,
    estimatedTime: "2 a 3 horas",
    isActive: true,
  },
  {
    id: "rate-paipa",
    department: "Boyacá",
    municipality: "Paipa",
    zone: "Casco Urbano Paipa",
    rateCOP: 6500,
    minOrderCOP: 25000,
    freeShippingFromCOP: 90000,
    estimatedTime: "60 a 90 min",
    isActive: true,
  },
  {
    id: "rate-sogamoso",
    department: "Boyacá",
    municipality: "Sogamoso",
    zone: "Casco Urbano Sogamoso",
    rateCOP: 8000,
    minOrderCOP: 30000,
    freeShippingFromCOP: 100000,
    estimatedTime: "Ruta Express diaria",
    isActive: true,
  },
  {
    id: "rate-tunja",
    department: "Boyacá",
    municipality: "Tunja",
    zone: "Casco Urbano Tunja",
    rateCOP: 7000,
    minOrderCOP: 30000,
    freeShippingFromCOP: 100000,
    estimatedTime: "Mismo día",
    isActive: true,
  },
  {
    id: "rate-nobsa",
    department: "Boyacá",
    municipality: "Nobsa",
    zone: "Valle de Sugamuxi (Nobsa / Tibasosa)",
    rateCOP: 7500,
    minOrderCOP: 25000,
    freeShippingFromCOP: 90000,
    estimatedTime: "1 a 2 horas",
    isActive: true,
  },
];

export const initialPickupPoints: PickupPoint[] = [
  {
    id: "pickup-duitama-centro",
    name: "Sede Principal Farmaboy - Duitama Centro",
    address: "Carrera 16 # 15-20, Centro, Duitama, Boyacá",
    municipality: "Duitama",
    phone: "+57 (608) 760-4422",
    coordinates: "5.8268, -73.0335",
    schedule: "Lunes a Sábado: 7:00 am - 9:00 pm | Domingos y Festivos: 8:00 am - 7:00 pm",
    days: "Lunes a Domingo",
    status: "ACTIVO",
    capacityOrdersPerDay: 80,
    prepTimeMinutes: 20,
    pickupInstructions: "Presenta tu cédula física y el número de pedido en la ventanilla de entregas rápidas (Módulo 1).",
  },
  {
    id: "pickup-duitama-plaza",
    name: "Farmaboy Plaza Los Libertadores",
    address: "Calle 16 # 14-45, Local 102, Duitama, Boyacá",
    municipality: "Duitama",
    phone: "+57 (608) 760-4423",
    coordinates: "5.8260, -73.0328",
    schedule: "Lunes a Sábado: 8:00 am - 8:00 pm",
    days: "Lunes a Sábado",
    status: "ACTIVO",
    capacityOrdersPerDay: 50,
    prepTimeMinutes: 30,
    pickupInstructions: "Indica tu código de pedido y nombre al farmacéutico de turno.",
  },
];
