import {
  UserProfile,
  Address,
  Order,
  RecurrentPurchase,
  ShoppingList,
  FamilyMember,
  MedicalPrescription,
  LoyaltyStatus,
  Coupon,
  PaymentMethodToken,
  BillingProfile,
  NotificationPreferences,
  SecuritySession,
  SecurityAuditLog,
  CompanyBranch,
  CorporateQuote,
} from "@/types/account";

export const initialMockUser: UserProfile = {
  id: "USR-770921",
  name: "Carlos",
  lastName: "Rodríguez Cárdenas",
  documentType: "CC",
  documentNumber: "1049628391",
  email: "carlos.rodriguez@email.com",
  isEmailVerified: true,
  phone: "312 456 7890",
  whatsapp: "312 456 7890",
  isPhoneVerified: true,
  birthDate: "1988-06-14",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80",
  accountType: "personal",
  companyName: "Distribuciones Boyacá S.A.S.",
  companyNit: "901.458.120-4",
  companyRole: "empresa_admin",
  lifetimeDiscountPercentage: 10,
  lifetimeDiscountReason: "Tratamiento Hipertensión / Cliente VIP Crónico (10% de por vida)",
  createdAt: "2025-01-15",
};

export const initialMockAddresses: Address[] = [];

export const initialMockOrders: Order[] = [
  {
    id: "FB-10842",
    date: "2026-09-04T14:30:00Z",
    status: "EN_CAMINO",
    items: [
      {
        id: "prod-1",
        name: "Acetaminofén 500 mg (Caja x 100 Tab)",
        quantity: 2,
        unitPrice: 12500,
        unitPriceDisplay: "$12.500 COP",
        totalPrice: 25000,
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
        category: "Medicamentos",
      },
      {
        id: "prod-3",
        name: "Suero Oral Electrolitos 500 ml (Manzana)",
        quantity: 4,
        unitPrice: 8900,
        unitPriceDisplay: "$8.900 COP",
        totalPrice: 35600,
        imageUrl: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=400&q=80",
        category: "Bienestar",
      },
    ],
    subtotal: 60600,
    shipping: 7000,
    discount: 5000,
    total: 62600,
    deliveryAddress: initialMockAddresses[0],
    paymentMethod: {
      type: "QR_BANCOLOMBIA",
      brand: "Código QR Bancolombia",
      lastFour: "1672",
    },
    courierName: "Domiciliario FarmaBoy Express (Tunja)",
    estimatedDelivery: "Hoy entre 5:30 pm y 6:30 pm",
    trackingSteps: [
      {
        step: "recibido",
        title: "Pedido recibido",
        description: "Tu orden fue confirmada en nuestra central FarmaBoy",
        date: "Hoy 2:30 pm",
        completed: true,
        isCurrent: false,
      },
      {
        step: "confirmado",
        title: "Pago aprobado",
        description: "Pago verificado por QR Bancolombia / Bre-B",
        date: "Hoy 2:32 pm",
        completed: true,
        isCurrent: false,
      },
      {
        step: "preparando",
        title: "Preparando en droguería",
        description: "El regente de farmacia verificó lote y empaque térmico",
        date: "Hoy 3:15 pm",
        completed: true,
        isCurrent: false,
      },
      {
        step: "en_camino",
        title: "En camino a tu dirección",
        description: "El domiciliario está en ruta hacia Carrera 2 Este # 58-30",
        date: "Hoy 4:10 pm",
        completed: false,
        isCurrent: true,
      },
      {
        step: "entregado",
        title: "Entregado",
        description: "Entrega firmada y recibida a satisfacción",
        completed: false,
        isCurrent: false,
      },
    ],
  },
  {
    id: "FB-09941",
    date: "2026-08-20T10:15:00Z",
    status: "ENTREGADO",
    items: [
      {
        id: "prod-4",
        name: "Alcohol Antiséptico 70% 1000 ml",
        quantity: 2,
        unitPrice: 14500,
        unitPriceDisplay: "$14.500 COP",
        totalPrice: 29000,
        imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80",
        category: "Cuidado de la Salud",
      },
      {
        id: "prod-2",
        name: "Ibuprofeno 800 mg (Caja x 30 Tab)",
        quantity: 1,
        unitPrice: 16800,
        unitPriceDisplay: "$16.800 COP",
        totalPrice: 16800,
        imageUrl: "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=400&q=80",
        category: "Medicamentos",
      },
      {
        id: "prod-6",
        name: "Tensiómetro Digital Automático de Brazo",
        quantity: 1,
        unitPrice: 145000,
        unitPriceDisplay: "$145.000 COP",
        totalPrice: 145000,
        imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80",
        category: "Equipos y Dispositivos",
      },
    ],
    subtotal: 190800,
    shipping: 0,
    discount: 0,
    total: 190800,
    deliveryAddress: initialMockAddresses[0],
    paymentMethod: {
      type: "QR_BANCOLOMBIA",
      brand: "QR Bancolombia / Bre-B",
    },
    trackingSteps: [
      {
        step: "recibido",
        title: "Pedido recibido",
        description: "Recibido en sistema",
        date: "20 Ago 10:15 am",
        completed: true,
        isCurrent: false,
      },
      {
        step: "confirmado",
        title: "Pago verificado",
        description: "Pago aprobado",
        date: "20 Ago 10:18 am",
        completed: true,
        isCurrent: false,
      },
      {
        step: "preparando",
        title: "Preparado en farmacia",
        description: "Empaque y control de calidad",
        date: "20 Ago 11:00 am",
        completed: true,
        isCurrent: false,
      },
      {
        step: "en_camino",
        title: "Despachado",
        description: "En ruta Tunja",
        date: "20 Ago 11:45 am",
        completed: true,
        isCurrent: false,
      },
      {
        step: "entregado",
        title: "Entregado a satisfacción",
        description: "Recibió Carlos Rodríguez",
        date: "20 Ago 12:30 pm",
        completed: true,
        isCurrent: false,
      },
    ],
  },
  {
    id: "FB-08712",
    date: "2026-07-12T16:00:00Z",
    status: "ENTREGADO",
    items: [
      {
        id: "prod-5",
        name: "Bloqueador Solar SPF 50+ Facial 60g",
        quantity: 2,
        unitPrice: 58000,
        unitPriceDisplay: "$58.000 COP",
        totalPrice: 116000,
        imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
        category: "Cuidado Personal",
      },
    ],
    subtotal: 116000,
    shipping: 0,
    discount: 10000,
    total: 106000,
    deliveryAddress: initialMockAddresses[0],
    paymentMethod: {
      type: "QR_BANCOLOMBIA",
      brand: "QR Bancolombia / Bre-B",
      lastFour: "1672",
    },
    trackingSteps: [],
  },
];

export const initialMockRecurrentPurchases: RecurrentPurchase[] = [
  {
    id: "rec-1",
    product: {
      id: "prod-1",
      name: "Acetaminofén 500 mg (Caja x 100 Tab)",
      price: 12500,
      priceDisplay: "$12.500 COP",
      imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
      category: "Medicamentos",
    },
    frequency: "MENSUAL",
    nextDeliveryDate: "2026-10-01",
    addressId: "addr-1",
    status: "ACTIVA",
    quantity: 2,
  },
  {
    id: "rec-2",
    product: {
      id: "prod-5",
      name: "Bloqueador Solar SPF 50+ Facial 60g",
      price: 58000,
      priceDisplay: "$58.000 COP",
      imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80",
      category: "Cuidado Personal",
    },
    frequency: "BIMESTRAL",
    nextDeliveryDate: "2026-11-15",
    addressId: "addr-1",
    status: "PAUSADA",
    quantity: 1,
  },
];

export const initialMockLists: ShoppingList[] = [
  {
    id: "list-1",
    name: "Botiquín Básico del Hogar",
    description: "Elementos esenciales para emergencias y malestares cotidianos",
    createdAt: "2026-02-10",
    items: [
      {
        id: "prod-1",
        name: "Acetaminofén 500 mg (Caja x 100 Tab)",
        price: 12500,
        priceDisplay: "$12.500 COP",
        imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80",
        category: "Medicamentos",
        quantity: 1,
      },
      {
        id: "prod-4",
        name: "Alcohol Antiséptico 70% 1000 ml",
        price: 14500,
        priceDisplay: "$14.500 COP",
        imageUrl: "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=400&q=80",
        category: "Cuidado de la Salud",
        quantity: 1,
      },
    ],
  },
  {
    id: "list-2",
    name: "Cuidado Adulto Mayor (Papá)",
    description: "Control de tensión y bienestar articular",
    createdAt: "2026-04-05",
    items: [
      {
        id: "prod-6",
        name: "Tensiómetro Digital Automático de Brazo",
        price: 145000,
        priceDisplay: "$145.000 COP",
        imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80",
        category: "Equipos y Dispositivos",
        quantity: 1,
      },
    ],
  },
];

export const initialMockFamily: FamilyMember[] = [];

export const initialMockPrescriptions: MedicalPrescription[] = [
  {
    id: "rx-101",
    patientName: "Carlos Rodríguez",
    doctorName: "Dr. Fernando Morales (Medicina General)",
    institution: "Centro Médico Boyacá",
    uploadDate: "2026-08-15",
    expirationDate: "2026-11-15",
    fileUrl: "#",
    fileName: "Formula_Medica_Agosto_2026.pdf",
    fileSize: "1.4 MB",
    fileType: "pdf",
    status: "VALIDADA",
    medicationsSummary: "Tratamiento preventivo para dolor muscular e hidratación",
  },
  {
    id: "rx-102",
    patientName: "María Cárdenas de Rodríguez",
    doctorName: "Dra. Lucía Salamanca (Cardiología)",
    institution: "Clínica Los Andes Tunja",
    uploadDate: "2026-09-02",
    expirationDate: "2026-12-02",
    fileUrl: "#",
    fileName: "Control_Presion_Mama.jpg",
    fileSize: "2.8 MB",
    fileType: "jpg",
    status: "VALIDADA",
    medicationsSummary: "Control de tensión arterial y multivitamínico",
  },
];

export const initialMockLoyalty: LoyaltyStatus = {
  tier: "Preferencial",
  points: 1250,
  pointsToNextTier: 750,
  nextTier: "Premium",
  availablePointsValueCOP: 12500,
  benefitsList: [
    "5% de descuento en medicamentos seleccionados los martes",
    "Envíos gratis en pedidos superiores a $60.000 COP",
    "Atención prioritaria por WhatsApp farmacéutico",
    "Recordatorio anticipado de formulaciones",
  ],
};

export const initialMockCoupons: Coupon[] = [
  {
    id: "coup-1",
    code: "BOYACA15",
    discountDisplay: "15% OFF",
    discountType: "PERCENTAGE",
    discountValue: 15,
    minPurchase: 50000,
    expiresAt: "2026-09-30",
    status: "DISPONIBLE",
    terms: "Válido para compras en Tunja, Duitama y Sogamoso. No acumulable.",
    categoryAllowed: "Medicamentos y Cuidado Personal",
  },
  {
    id: "coup-2",
    code: "FARMAFIESTA",
    discountDisplay: "$10.000 COP",
    discountType: "FIXED",
    discountValue: 10000,
    minPurchase: 80000,
    expiresAt: "2026-10-15",
    status: "DISPONIBLE",
    terms: "Aplica en toda la tienda para órdenes superiores a $80.000 COP.",
  },
  {
    id: "coup-3",
    code: "BIENVENIDA",
    discountDisplay: "10% OFF",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minPurchase: 30000,
    expiresAt: "2026-06-30",
    status: "USADO",
    terms: "Cupón de bienvenida redimido en tu primer pedido.",
  },
  {
    id: "coup-4",
    code: "JULIOVERANO",
    discountDisplay: "$5.000 COP",
    discountType: "FIXED",
    discountValue: 5000,
    minPurchase: 45000,
    expiresAt: "2026-07-31",
    status: "VENCIDO",
    terms: "Campaña de mitad de año.",
  },
];

export const initialMockPaymentMethods: PaymentMethodToken[] = [
  {
    id: "pm-1",
    brand: "VISA",
    lastFour: "4821",
    holderName: "CARLOS RODRIGUEZ",
    expiry: "09/28",
    isDefault: true,
  },
  {
    id: "pm-2",
    brand: "MASTERCARD",
    lastFour: "9012",
    holderName: "CARLOS RODRIGUEZ",
    expiry: "03/27",
    isDefault: false,
  },
  {
    id: "pm-3",
    brand: "PSE_BANCOLOMBIA",
    holderName: "Carlos Rodríguez Cárdenas",
    isDefault: false,
  },
];

export const initialMockBillingProfile: BillingProfile = {
  type: "PERSONA_NATURAL",
  nameOrBusinessName: "Carlos Rodríguez Cárdenas",
  documentType: "CC",
  documentNumber: "1049628391",
  taxEmail: "carlos.facturacion@email.com",
  fiscalAddress: "Carrera 2 Este # 58-30 Torre 3 Apto 502",
  city: "Tunja, Boyacá",
  phone: "312 456 7890",
};

export const initialMockNotificationPreferences: NotificationPreferences = {
  channels: {
    email: true,
    whatsapp: true,
    sms: false,
    push: true,
  },
  categories: {
    orderStatus: true,
    deliveryTracking: true,
    payments: true,
    couponsAndDiscounts: true,
    promotions: false,
    medicineReminders: true,
    newsletters: false,
  },
};

export const initialMockSessions: SecuritySession[] = [
  {
    id: "sess-1",
    device: "MacBook Pro 16”",
    browser: "Chrome 128 (macOS)",
    location: "Tunja, Boyacá",
    ipAddress: "186.84.92.14",
    lastActive: "Activo ahora",
    isCurrent: true,
  },
  {
    id: "sess-2",
    device: "iPhone 15 Pro",
    browser: "Safari Mobile (iOS)",
    location: "Tunja, Boyacá",
    ipAddress: "190.158.204.88",
    lastActive: "Hace 2 horas",
    isCurrent: false,
  },
];

export const initialMockAuditLogs: SecurityAuditLog[] = [
  {
    id: "log-1",
    event: "Inicio de sesión exitoso",
    date: "Hoy 14:15",
    ip: "186.84.92.14",
    device: "Chrome / macOS",
    status: "EXITOSO",
  },
  {
    id: "log-2",
    event: "Dirección actualizada (Casa)",
    date: "Ayer 18:40",
    ip: "186.84.92.14",
    device: "Chrome / macOS",
    status: "EXITOSO",
  },
  {
    id: "log-3",
    event: "Fórmula médica subida",
    date: "02 Sep 11:22",
    ip: "190.158.204.88",
    device: "Safari Mobile / iOS",
    status: "EXITOSO",
  },
];

export const initialMockBranches: CompanyBranch[] = [
  {
    id: "branch-1",
    name: "Sede Principal Tunja",
    city: "Tunja",
    address: "Carrera 10 # 24-50 Centro",
    phone: "312 456 7890",
    managerName: "Carlos Rodríguez (Gerente de Operaciones)",
    managerEmail: "crodriguez@distribucionesboyaca.com",
    isMainBranch: true,
  },
  {
    id: "branch-2",
    name: "Bodega Logística Duitama",
    city: "Duitama",
    address: "Avenida Las Américas # 12-80 Bodega 4",
    phone: "310 987 6543",
    managerName: "Ing. Javier Mendoza",
    managerEmail: "jmendoza@distribucionesboyaca.com",
    isMainBranch: false,
  },
  {
    id: "branch-3",
    name: "Punto Asistencial Sogamoso",
    city: "Sogamoso",
    address: "Calle 11 # 14-22 Barrio El Sol",
    phone: "315 222 3344",
    managerName: "Dra. Marcela Silva",
    managerEmail: "msilva@distribucionesboyaca.com",
    isMainBranch: false,
  },
];

export const initialMockQuotes: CorporateQuote[] = [
  {
    id: "quot-101",
    code: "COT-2026-088",
    title: "Dotación Insumos Hospitalarios y Botiquines Industriales",
    date: "2026-08-28",
    validUntil: "2026-09-28",
    status: "COTIZADA",
    totalEstimatedCOP: 3850000,
    itemsCount: 18,
    branchName: "Bodega Logística Duitama",
  },
  {
    id: "quot-102",
    code: "COT-2026-054",
    title: "Suministro Mensual Guantes de Nitrilo, Tapabocas y Alcohol",
    date: "2026-08-05",
    validUntil: "2026-09-05",
    status: "APROBADA",
    totalEstimatedCOP: 1940000,
    itemsCount: 8,
    branchName: "Sede Principal Tunja",
  },
];
